#!/bin/bash

# Run this script by `SWIFT_EXEC=/Volumes/Shared/Git/MyProjects/swift-everywhere-toolchain/.unused/swiftc-arm-linux-androideabi swift build -c release -Xswiftc -sdk -Xswiftc /Volumes/Shared/Git/MyProjects/swift-everywhere-toolchain/ToolChain/swift-android-toolchain`

/Volumes/Shared/Git/MyProjects/swift-everywhere-toolchain/ToolChain/swift-android-toolchain/usr/bin/swiftc \
-v -Xcc -v \
-target armv7-none-linux-androideabi \
-tools-directory /Users/lihanguang/dev_kit/sdk/android_sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin \
-Xclang-linker --sysroot=/Users/lihanguang/dev_kit/sdk/android_sdk/ndk/21.3.6528147/platforms/android-24/arch-arm \
-Xclang-linker --gcc-toolchain=/Users/lihanguang/dev_kit/sdk/android_sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64 \
-Xcc -I/Users/lihanguang/dev_kit/sdk/android_sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include \
-Xcc -I/Users/lihanguang/dev_kit/sdk/android_sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/arm-linux-androideabi \
-L /Users/lihanguang/dev_kit/sdk/android_sdk/ndk/21.3.6528147/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a \
-L /Users/lihanguang/dev_kit/sdk/android_sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x \
-L /Users/lihanguang/dev_kit/sdk/android_sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/lib/arm-linux-androideabi/24 \
-L /Volumes/Shared/Git/MyProjects/swift-everywhere-toolchain/ToolChain/swift-android-toolchain/usr/lib/swift/android/armv7 \
$@
